version: 2

workflows:
  single-node:
    steps:
      -
        name: "train single-node"
        command: experiment.run_single_node
        params:
          command: python mnist.py
          container: tensorflow/tensorflow:1.13.1-gpu-py3
          clusterId: clq6q1qt0
          machineType: "P4000"
          modelPath: "/artifacts"
          modelType: "Tensorflow"
          
