version: 2

workflows:
  single-node:
    steps:
      -
        name: "train single-node"
        command: experiment.run_single_node
        params:
          command: python mnist.py
          container: tensorflow/tensorflow:1.13.1-gpu-py3
          experimentEnv:
            EPOCHS_EVAL: 5
            EVAL_SECS: 10
            MAX_STEPS: 20
            TRAIN_EPOCHS: 3
          clusterId: clq6q1qt0
          machineType: P4000
          modelPath: /artifacts
          modelType: Tensorflow
          
